server:
  port: 8083

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://ch_survey_service:SurveyCH639@ec2-43-204-97-157.ap-south-1.compute.amazonaws.com:27017/ch_survey_db?retryWrites=true&w=majority&authSource=admin
      database: ch_survey_db
      authentication-database: admin
      auto-index-creation: true

keycloak:
  auth-server-url: https://ec2-43-204-97-157.ap-south-1.compute.amazonaws.com:8443
  realm: cohotz
  resource: cohotz-service
  public-client: true
  bearer-only: true
  principal-attribute: preferred_username
  use-resource-role-mappings: false
  security-constraints:
    - authRoles:
        - user
        - admin