cohotz:
  app:
    name: Survey Service
    description: Cohotz Survey Microservice
    version: 1.0
  crypto:
    enabled: ${COHOTZ_ENCRYPTION_ENABLED:true}
    secret: ORyEeljxwxwkJeE1i9UShars8fgfKZ1c
    salt: NMzMpHb8mv
  clients:
    cohotz-core-service:
      url: ${COHOTZ_CORE_SERVICE_HOST:http://localhost:8081}
      oauth2:
        enabled: ${COHOTZ_CORE_SERVICE_OAUTH_ENABLED:true}
        client-id: cohotz-service
        client-secret: ${COHOTZ_CORE_SERVICE_SECRET}
        access-token-url: http://${COHOTZ_KEYCLOAK_HOST:localhost}:8080/auth/realms/cohotz/protocol/openid-connect/token
        provider-id: cohotz-core-service
    cohotz-profile-service:
      url: ${COHOTZ_PROFILE_SERVICE_HOST:http://localhost:8083}
      oauth2:
        enabled: ${COHOTZ_PROFILE_SERVICE_OAUTH_ENABLED:true}
        client-id: cohotz-service
        client-secret: ${COHOTZ_PROFILE_SERVICE_SECRET}
        access-token-url: http://${COHOTZ_KEYCLOAK_HOST:localhost}:8080/auth/realms/cohotz/protocol/openid-connect/token
        provider-id: cohotz-profile-service
    cohotz-record-service:
      url: ${COHOTZ_RECORD_SERVICE_HOST:http://localhost:8085}
      oauth2:
        enabled: ${COHOTZ_RECORD_SERVICE_OAUTH_ENABLED:true}
        client-id: cohotz-service
        client-secret: ${COHOTZ_PROFILE_SERVICE_SECRET}
        access-token-url: http://${COHOTZ_KEYCLOAK_HOST:localhost}:8080/auth/realms/cohotz/protocol/openid-connect/token
        provider-id: cohotz-record-service
  micro-culture:
    reportee-threshold: 2
    caching: ${COHOTZ_MICRO_CULTURE_CACHING:false}
  email.enabled: ${COHOTZ_ENABLED_EMAIL:false}

server:
  port: ${COHOTZ_SERVICE_PORT:8083}
  forward-headers-strategy: framework
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://ch_survey_service:SurveyCH639@${COHOTZ_MONGODB_HOST:localhost}:27017/ch_survey_db?retryWrites=true&w=majority&authSource=admin
      database: ch_survey_db
      authentication-database: admin
      auto-index-creation: true
  thymeleaf:
    cache: false
    mode: HTML

kafka:
  enabled: ${COHOTZ_KAFKA_ENABLED:false}
  bootstrapAddress: "13.235.73.51:9092"
  schemaRegistry: "http://13.235.73.51:8585"
  username: ${COHOTZ_KAFKA_CLUSTER_USERNAME:cohotz}
  password: ${COHOTZ_KAFKA_CLUSTER_PASSWORD:Cohotz@486Kafka}
  sasl-enabled: ${COHOTZ_SASL_ENABLED:true}
keycloak:
  enabled: ${COHOTZ_AUTH_ENABLED:true}
  ssl-required: none
  auth-server-url: http://${COHOTZ_KEYCLOAK_HOST:localhost}:8080/auth
  realm: cohotz
  resource: cohotz-service
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username
  use-resource-role-mappings: false
  security-constraints:
    - authRoles:
        - user
        - admin

resilience4j:
  retry:
    retry-aspect-order: 2
    instances:
      cohotz-core-service:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
        ignore-exceptions:
          - org.cohotz.boot.error.CHException
      cohotz-profile-service:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
        ignore-exceptions:
          - org.cohotz.boot.error.CHException
      cohotz-record-service:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
        ignore-exceptions:
          - org.cohotz.boot.error.CHException
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      cohotz-core-service:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
        record-exceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
      cohotz-profile-service:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
        record-exceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
      cohotz-record-service:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
        record-exceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException

survey:
  cohorts:
    department: Department
    workLocation: Location
    currentExperience: Tenure
    totalExperience: Experience
  update-delay: 300000
  scheduler:
    enabled: true
    frequency: 30000
    tenants:
      - COHOTZ
  smart-threshold: 3
  survey-link-format: "https://app.cohotz.com/survey/%s/%s/%s"
  status-map:
    DRAFT:
      - PUBLISHED
      - STARTED
      - CANCELLED
    ERROR:
      - PUBLISHED
    PUBLISHED:
      - STARTED
      - CANCELLED
    CANCELLED:
    IN_PROGRESS:
      - AUTO_COMPLETE
      - MARKED_COMPLETE
    AUTO_COMPLETE:
    MARKED_COMPLETE:

sib:
  api-key: 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
  url: https://api.sendinblue.com/v3/smtp/email