spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://ch_survey_service:SurveyCH639@localhost:27017/ch_survey_db_test?retryWrites=true&w=majority&authSource=admin
      database: ch_survey_db_test
      authentication-database: admin
      auto-index-creation: true

keycloak:
  enabled: false
  auth-server-url: http://localhost:8080/auth
  realm: cohotz
  resource: cohotz-profile-service
  public-client: true
  bearer-only: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - user
        - admin