cohotz:
  clients:
    cohotz-core-service:
      url: "http://cohotz-core-service:8080"
    cohotz-profile-service:
      url: "http://cohotz-profile-service:8080"
    cohotz-record-service:
      url: "http://cohotz-record-service:8080"

keycloak:
  ssl-required: none