cohotz:
  clients:
    cohotz-core-service:
      url: "http://cohotz-core-service:8080"
    cohotz-profile-service:
      url: "http://cohotz-profile-service:8080"
server:
  port: 8080

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://ch_survey_service:SurveyCH639@mongodb:27017/ch_survey_db?retryWrites=true&w=majority&authSource=admin
      database: ch_survey_db
      authentication-database: admin
      auto-index-creation: true

keycloak:
  enabled: true
  auth-server-url: http://localhost:8080
  realm: cohotz
  resource: cohotz-profile-service
  public-client: true
  bearer-only: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - user
        - admin